-- Migration: normalize_3nf_expand
-- Generated by: db-tune-and-report skill — Step 3 (Migration Risk Review)
-- Phase: EXPAND — all additive, nothing dropped
-- Contract phase (separate future migration after app cutover):
--   ALTER TABLE "Candidate" ALTER COLUMN "addressId" SET NOT NULL;
--   ALTER TABLE "Candidate" DROP COLUMN "address";
--   ALTER TABLE "Position"  DROP COLUMN "companyDescription";
--   UPDATE "Resume" SET "fileTypeParsed" = CASE WHEN "fileType" ILIKE '%pdf%' THEN 'PDF'::"FileType" ELSE 'DOCX'::"FileType" END WHERE "fileTypeParsed" IS NULL;
--   ALTER TABLE "Resume" DROP COLUMN "fileType";
--   ALTER TABLE "Resume" RENAME COLUMN "fileTypeParsed" TO "fileType";

-- ── 1. Address table ───────────────────────────────────────────────────────
CREATE TABLE "Address" (
  "id"         SERIAL        NOT NULL,
  "street"     VARCHAR(200),
  "city"       VARCHAR(100)  NOT NULL,
  "region"     VARCHAR(100),
  "postalCode" VARCHAR(20),
  "country"    VARCHAR(100)  NOT NULL,
  "createdAt"  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"  TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "Address_pkey" PRIMARY KEY ("id")
);

-- Dedup constraint (user decision Q5, Step 1)
CREATE UNIQUE INDEX "Address_street_city_postalCode_country_key"
    ON "Address" ("street", "city", "postalCode", "country");

-- Geographic filter index
CREATE INDEX "Address_city_country_idx"
    ON "Address" ("city", "country");

-- ── 2. Candidate.addressId (nullable FK, one-to-one) ──────────────────────
ALTER TABLE "Candidate" ADD COLUMN "addressId" INTEGER;

ALTER TABLE "Candidate"
    ADD CONSTRAINT "Candidate_addressId_fkey"
    FOREIGN KEY ("addressId") REFERENCES "Address"("id")
    ON UPDATE CASCADE ON DELETE RESTRICT;

-- Enforces one-to-one (NULL ≠ NULL so multiple NULL rows are allowed during expand)
CREATE UNIQUE INDEX "Candidate_addressId_key"
    ON "Candidate" ("addressId");

-- ── 3. Company.description (additive) ────────────────────────────────────
ALTER TABLE "Company" ADD COLUMN "description" TEXT;

-- ── 4. FileType enum ──────────────────────────────────────────────────────
CREATE TYPE "FileType" AS ENUM ('PDF', 'DOCX');

-- ── 5. Resume.fileTypeParsed (expand alongside legacy fileType VARCHAR) ───
ALTER TABLE "Resume" ADD COLUMN "fileTypeParsed" "FileType";
