-- Migration: optimize_r4_stalled_partial_idx
-- Generated by: db-tune-and-report skill — Step 5 (Optimize R4)
-- Phase: ADDITIVE — index only, nothing dropped or altered
--
-- Purpose: accelerate the status NOT IN ('HIRED','REJECTED','WITHDRAWN') filter
-- used by R4 (Stalled Applications) and any other active-application query.
-- At production scale (≥ 10K Application rows) this converts a sequential scan
-- of the full Application table into a partial index scan covering only active rows.
--
-- Refresh / staleness: none — this is a standard btree index maintained
-- automatically by PostgreSQL on every INSERT / UPDATE / DELETE.
--
-- Rollback: DROP INDEX CONCURRENTLY "Application_active_status_idx";

CREATE INDEX "Application_active_status_idx"
    ON "Application" ("status")
    WHERE status NOT IN ('HIRED', 'REJECTED', 'WITHDRAWN');
