-- Migration: add_common_query_indexes
-- Generated by: db-tune-and-report skill — Step 2
-- Indexes: I1 (composite), I2 (partial), I3 (partial)

-- I1: Interview(employeeId, interviewDate) composite
-- Serves Q4 (employee calendar date-range) and Q11 (top interviewers last 30 days)
-- Replaces the single-column employeeId_idx for date-range + employee queries
CREATE INDEX "Interview_employeeId_interviewDate_idx"
    ON "Interview" ("employeeId", "interviewDate");

-- I2: Position partial index — open visible positions by employment type
-- Serves Q9 (job board search by type + salary range)
-- Partial: only indexes rows where status='OPEN' AND isVisible=true
CREATE INDEX "Position_open_visible_employmentType_idx"
    ON "Position" ("employmentType")
    WHERE status = 'OPEN' AND "isVisible" = true;

-- I3: Position partial index — open positions by age
-- Serves Q12 (stale open positions with zero applications)
-- Partial: only indexes rows where status='OPEN'
CREATE INDEX "Position_open_createdAt_idx"
    ON "Position" ("createdAt")
    WHERE status = 'OPEN';
